### ISSUE TITLE
Using by huggingface model

### ISSUE THREAD

**Issue by miziworld** [Masao-Someki/espnet_onnx#13]
Hello, this project looks very useful to me

Is it possible to use this project as a registered model on huggingface ( ASR model- VGGRNN) ?
If so, how should I use tag name or model_dir?

I have pth file trained on Espnet, can I convert pth model to onnx by using this project?

**Comment by Masao-Someki** [comment]
Hi, @miziworld 
Thank you for using this project!

> Is it possible to use this project as a registered model on huggingface ( ASR model- VGGRNN) 

About the `espnet.nets.pytorch_backend.rnn.VGG2L` model, it is not tested yet. I think the `VGG2L` model can be exported to onnx with the current code, but I will test it this weekend...
If the decoder and LM model are marked as supported in [this document](https://github.com/Masao-Someki/espnet_onnx/blob/master/doc/ASRSupported.md), then you can export that model.


> If so, how should I use tag name or model_dir?

When exporting a pretrained model, `model_dir` is not required. `tag_name` in `export_from_pretrained` is to download pretrained model listed in `table.csv` of `espnet_model_zoo`. 

> I have pth file trained on Espnet, can I convert pth model to onnx by using this project?

Yes. If you want to export your own model, then you have to use `export`. 
First, please be sure that the encoder/decoder/lm models are all supported.
Second, you have to convert your pretrained model into the `espnet2.bin.asr_inference.Speech2Text` instance. 
Finally, you can export to onnx format with the following code.
```python
from espnet2.bin.asr_inference import Speech2Text
speech2text = Speech2Text(args)
m.export(speech2text, '<tag name>', quantize=True)
```
`tag_name` in this `export` function is to define the model name. You can load your own exported model with the `tag_name`.

> Also, have you ever done a successful onnx convert for asr model?

Yes. I tried with `kamo-naoyuki/timit_asr_train_asr_raw_word_valid.acc.ave` and finished successfully..
Maybe your `espnet_onnx` is not the latest version, so please check if the `espnet_onnx` is the latest.

![Screenshot from 2022-04-05 00-27-44](https://user-images.githubusercontent.com/44265101/161579106-4f7be094-16e9-4f25-80a3-a9ecd903cd0f.png)
![Screenshot from 2022-04-05 00-26-10](https://user-images.githubusercontent.com/44265101/161579130-8140f28a-dbba-41d5-ac7e-0558c08b2f1e.png)

**Comment by Masao-Someki** [comment]
Sorry, I misunderstood your question..

> In this case, I think tag_name will not be in table.csv, is that possible?

It is not possible. `export_from_pretrained` can only be used to export from `table.csv`.

> Is it possible to use the zip file in the path like the existing espnet's d=ModelDownloader()?

Yes. Note that you need to create an instance of `espnet2.bin.asr_inference.Speech2Text` from your zip file, and need to use the `export` function.

I will check with the docker environment..

**Comment by miziworld** [comment]
Thank you for your reply.
As I said, this feature is absolutely necessary for me, so I can only hope that the problem will be resolved soon.
I think the attn problem is related to pytorch or onnx rather than virtual environment problem. Can you tell me the environment you are using? (pytorch, venv, espnet, ...)

And if you find a solution, please share your answer. thank you

**Comment by Masao-Someki** [comment]
> I think the attn problem is related to pytorch or onnx rather than virtual environment problem. Can you tell me the environment you are using? (PyTorch, venv, espnet, ...)

I'm using the stable versions of PyTorch, espnet, and some other requirements. (I installed with `pip install torch espnet ...`) When I tested with your environment, I realized that model exportation with torch==1.10.1 could cause that error. I think upgrading your torch version to 1.11 can solve this problem. (In my environment, torch==1.10.1 cases that error, but torch==1.11.0 does not.)

Would you update your torch version, and see if the error would be fixed?

**Comment by miziworld** [comment]
Thank you!
As you said, after converting the torch version 1.10.1 --> 1.11.0, it seemed to work fine.
After export, I got some files 
  --- ~/.cache/espnet_onnx/kamo-naoyuki/timit_asr_train_asr_raw_word_valid.acc.ave/full/
 ------------|
-------------|_____ ctc.onnx, decoder.onnx, encoder.onnx, predecoder_0.onnx
Is this right?
And i have some questions.
1. When I use the quantizaiton option, which layer is it applied to? Is this not quantization of espnet, but quantization of dtype as a whole while converting to onnx?
2.  How do I know which file is created after exporting? (encoder, decoder, ctc....)
3.  As you said like this to use my own model (.zip)
```
from espnet2.bin.asr_inference import Speech2Text
speech2text = Speech2Text(args)
m.export(speech2text, '<tag name>', quantize=True)
```
if i have the model(.zip file) in the directory /root/example_rnn.zip
how can i fix the export_asr.py to use d=ModelDownloader() of ESPNet?
4. What does the inference code you posted mean? When I thought, when I put the test.wav file, it seems to find and output nbest, but when I run it, the following result comes out.
![image](https://user-images.githubusercontent.com/17849068/162253910-8c0b5718-1c63-4862-a23c-a2704936c65d.png)

**Comment by Masao-Someki** [comment]
I'm glad it went well. 
> Is this right?

Yes, the model was exported correctly.

> When I use the quantization option, which layer is it applied to? Is this not quantization of espnet, but quantization of dtype as a whole while converting to onnx?

The quantization is applied to all layers applicable. In this repo, I used the default onnx quantization tool provided [here](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/quantization/README.md). Since only `encoder`, `decoder`, `ctc`, `language model` in espnet will be converted to onnx and can be quantized, so quantization option will not be applied to the whole computation of `espnet2.bin.inference.Speech2Text`.

> How do I know which file is created after exporting? (encoder, decoder, ctc....)

Currently, you need to check which component the model contains, and you have to check that every onnx model exists. I think it's nice to have such a log, so I will add a new log (and options) to print the file names which should be exported.

> how can i fix the export_asr.py to use d=ModelDownloader() of ESPNet?

If you are trying to use `espnet_model_zoo` to load your original model, then I think `espnet_model_zoo` will not provide such functionality. You have to create ` espnet2.bin.inference.Speech2Text` instance with some arguments.

Please check the following steps to load your model.
1. Unzip your file. Please make sure that you have the following files.
- pretrained asr model and config.yaml.
- feats_stats.npz in the correct directory. (The directory should be in the config.yaml)
- language model file and config file, if you use LM.
2. Instantiate the Speech2Text class.
```python
speech2text = Speech2Text(
  asr_train_config="path/to/training/config",
  asr_model_file="path/to/model/file",
  lm_train_config="path/to/lm/config",
  lm_file="path/to/lm/file"
)
```
Then you can use `speech2text` to use asr.

> What does the inference code you posted mean? When I thought, when I put the test.wav file, it seems to find and output nbest, but when I run it, the following result comes out.

It shows how to compute `nbest` with exported onnx files. The `nbest` for the result is equal to what the `espnet2.bin.inference.Speech2Text` returns. However, I modified it to return only one hypothesis, so as `nbest` you will get `[(text, token, token_int, hypothesis object)]`.  Estimated text for the wav file will be stored in the `nbest[0][0]`.

**Comment by miziworld** [comment]
Thank you so much for your kind and detailed reply.
1. However, the following Import Error occurred while executing the same code. There is no special environment change, how do I solve it?
 
![image](https://user-images.githubusercontent.com/17849068/164012412-b310df4f-18d6-4f3d-a6dd-a2b7a3e97ac8.png)

onnx. py is like this.
```
from espnet2.bin.asr_inference import Speech2Text                                                                                                                                                                                                                                                                                                                          from espnet_onnx.export import ModelExport                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            m=ModelExport()                                                                                                                                                                                                                                                                                                                                                            m.export_from_pretrained('kamo-naoyuki/timit_asr_train_asr_raw_word_valid.acc.ave')                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   speech2text=Speech2Text(args)                                                                                                                                                                                                                                                                                                                                              #m.export(speech2text, 'kamo-naoyuki/timit_asr_train_asr_raw_word_valid.acc.ave')                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     import librosa                                                                                                                                                                                                                                                                                                                                                             from espnet_onnx import Speech2Text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   speech2text=Speech2Text('kamo-naoyuki/timit_asr_train_asr_raw_word_valid.acc.ave')                                                                                                                                                                                                                                                                                         y,sr=librosa.load('test1.wav',sr=16000)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               nbest=speech2text(y)
```                                                                                                                                                                                                                                                                                                                                                                                      
2. As you said, after decompressing the zip file of the RNNencoder-RNNdecoder model that I trained, I put the arguments as follows. However, the conversion is not done with the following error:
onnx.py is like this.
```
from espnet2.bin.asr_inference import Speech2Text                                                                                                                                                                                                                                                                                                                          #from espnet_onnx.export import ModelExport                                                                                                                                                                                                                                                                                                                                #import espnet                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        #m=ModelExport()                                                                                                                                                                                                                                                                                                                                                           #m.export_from_pretrained('kamo-naoyuki/timit_asr_train_asr_raw_word_valid.acc.ave')                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  #speech2text=Speech2Text(args)                                                                                                                                                                                                                                                                                                                                             #m.export(speech2text, 'kamo-naoyuki/timit_asr_train_asr_raw_word_valid.acc.ave')                                                                                                                                                                                                                                                                                          speech2text=Speech2Text(                                                                                                                                                                                                                                                                                                                                                           asr_train_config="./rnn_onnx/exp/asr_train_asr_rnn_raw_kr_bpe2309/config.yaml",                                                                                                                                                                                                                                                                                            asr_model_file="./rnn_onnx/exp/asr_train_asr_rnn_raw_kr_bpe2309/valid.acc.ave_10best.pth",                                                                                                                                                                                                                                                                         ) 
```                                                                                                            
![image](https://user-images.githubusercontent.com/17849068/164014360-d5f5d616-1a32-4d47-bd16-714eb91ab061.png)

I'll attach the code I ran and config.yaml.
/opt/espnet_onnx/rnn_onnx
--------------/exp
------------------/asr_stats_raw_kr_bpe2309
------------------/asr_train_asr_rnn_raw_kr_bpe2309
------------------------------/RESULTS.md
------------------------------/config.yaml
------------------------------/valid.acc.ave_10best.pth
[config.yaml.txt](https://github.com/Masao-Someki/espnet_onnx/files/8513490/config.yaml.txt)

**Comment by Masao-Someki** [comment]
> However, the following Import Error occurred while executing the same code. There is no special environment change, how do I solve it?

Sorry, you need to install `onnx` additionally to use `ModelExport`. I completely forgot to note that `onnx` is required...
Could you install onnx and try again?

> As you said, after decompressing the zip file of the RNNencoder-RNNdecoder model that I trained, I put the arguments as follows. However, the conversion is not done with the following error:

Your code is to create the instance of `espnet2.bin.asr_inference.Speech2Text`. You need to use that instance to export like the following.

```python
# Your code
from espnet2.bin.asr_inference import Speech2Text    
speech2text=Speech2Text(   
  asr_train_config="./rnn_onnx/exp/asr_train_asr_rnn_raw_kr_bpe2309/config.yaml", 
  asr_model_file="./rnn_onnx/exp/asr_train_asr_rnn_raw_kr_bpe2309/valid.acc.ave_10best.pth",   
) 

# you need to add the following code to export model.
from espnet_onnx.export import ModelExport
m = ModelExport()
m.export(
  model=speech2text,
  tag_name='<tag_name of the model>'
)
```
