### ISSUE TITLE
Decoding speed difference between before and after conversion

### ISSUE THREAD

**Issue by miziworld** [Masao-Someki/espnet_onnx#22]
Thank you for your always kind reply. Also, your research has really helped me a lot.

In general, the purpose of onnx conversion is to make the model lighter and get faster speed. Have you ever checked the difference in decoding speed before and after conversion onnx model conversion in the asr task? I would also like to know if there is also a difference in accuracy. It doesn't matter which model you've been running.

**Comment by Masao-Someki** [comment]
> Have you ever checked the difference in decoding speed before and after conversion onnx model conversion in the asr task?

Yes, I checked inference speed every time I implement the new model. Onnx model with RNN related models, such as RNNEncoder, decoder, or seqrnn-lm improves its inference speed very much. See comments in #10 for example!
However, transformer/conformer-based models will not improve their inference speed as the RNN models. It seems that the conversion script cannot optimize the Residual block, which generates a lot of nodes in the onnx graph.
I'm planning to implement the optimization option to simplify the onnx graph in `feature/model_optimize` branch, and I think quantization with this optimization will speed up about x2~x3. Reference: see [this article](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/transformers/notebooks/PyTorch_Bert-Squad_OnnxRuntime_GPU.ipynb) for Bert optimization. 

> I would also like to know if there is also a difference in accuracy.

Sorry, I didn't compare the accuracy between the torch and onnx models, but I'm sure that the model output will not differ so much. In the CI test, there are some tests for model output, which calculate the MSE to confirm the two models output the same result.

**Comment by miziworld** [comment]
Thank you for reply.
1. Did you notice any speedup when testing conformer/transformer models?
2. Have you ever tried gpu decoding? In the original espnet, decoding takes longer when using gpu decoding, but I'm curious to see what the results are for this project.
3. Other than onnx conversion, have you ever tried increasing the inference speed of this asr model or compressing the model? I'm researching on this, and it would be very helpful if you could give me an answer.

**Comment by Masao-Someki** [comment]
Hi @miziworld,

> Did you notice any speedup when testing conformer/transformer models?
> Have you ever tried gpu decoding? In the original espnet, decoding takes longer when using gpu decoding, but I'm curious to see what the results are for this project.

Yes, there is a little improvement in those models if you execute inference on the CPU. If you run inference on the GPU, then the torch version is the fastest. See #16 for example.

> Other than onnx conversion, have you ever tried increasing the inference speed of this asr model or compressing the model? 

No, for now, I have never tried to optimize the original espnet models for inference.
