### ISSUE TITLE
a small bug

### ISSUE THREAD

**Issue by unparalleled-ysj** [Masao-Someki/espnet_onnx#23]
@Masao-Someki Hi, thank you very much for completing the onnx export of vits. After the test of my own training model, when I set cleaner=none, there was a small problem, and after solving everything works fine !
`File "/work/ysj/espnet_onnx/espnet_onnx/export/tts/get_config.py", line 46, in get_preprocess_config
    'cleaner_types': model.text_cleaner.cleaner_types[0]
IndexError: list index out of range`

**Comment by unparalleled-ysj** [comment]
@Masao-Someki BTW, want to call the converted vits onnx model with C++, do you have any relevant examples can recommend?

**Comment by Masao-Someki** [comment]
Hi @unparalleled-ysj,
Thank you for reporting the bug! I'm planning to refactor this project, so I will fix it in the next PR!

> BTW, want to call the converted vits onnx model with C++, do you have any relevant examples can recommend?

Sorry, I'm not familiar with C++, so I cannot give you examples for C++ implementation...
I think [this repository](https://github.com/microsoft/onnxruntime-inference-examples/tree/main/c_cxx) might help you how to use models from C++. The model input and output of the converted onnx models are defined in [here](https://github.com/Masao-Someki/espnet_onnx/blob/a5e0882abe6eb471f68c6f111583e2c32e2b82e3/espnet_onnx/export/tts/models/tts_models/vits.py#L261-L286), but you can also get them from the following python snippet.

```python
from espnet_onnx import Text2Speech

tag_name = 'some model name'
onnx_model = Text2Speech(tag_name)

# get information about input argument for example.
for d in onnx_model.tts_model.model.get_inputs():
    print((d.name, d.shape, d.type))
# ('text', ['text_length'], 'tensor(int64)')
# ('text_length', [1], 'tensor(int64)')

# and get information about outputs
for d in onnx_model.tts_model.model.get_outputs():
    print((d.name, d.shape, d.type))
# ('wav', ['wav_length'], 'tensor(float)')
# ('att_w', ['att_w_feat_length', 'att_w_text_length'], 'tensor(float)')
# ('dur', ['dur_length'], 'tensor(float)')

```

**Comment by unparalleled-ysj** [comment]
The bug still exists because model.text_cleaner is an address while text_cleaner=None

`def get_preprocess_config(model, path):
    ret = {}
    if model.text_cleaner is not None:
        ret.update({'text_cleaner': {
                'cleaner_types': model.text_cleaner.cleaner_types[0]
        }})
    else:
        ret.update({'text_cleaner': None})
        
    ret.update({'tokenizer': get_tokenizer_config(model.tokenizer, path)})
    return ret`

**Comment by Masao-Someki** [comment]
Thank you!
I realized that I need to change the following part to `if clearner_config is not None`
I'm planning to fix some bugs related to TTS this weekend, so I will fix this part with it!
https://github.com/Masao-Someki/espnet_onnx/blob/8bb9d7798b3b52b3b04c966a978d35c036c70ed7/espnet_onnx/tts/model/preprocess/common_processor.py#L12-L15
