### ISSUE TITLE
quantize model take very long time to synthesis

### ISSUE THREAD

**Issue by ly1984** [Masao-Someki/espnet_onnx#25]
I've test a sentence with these three models, the quantize model seems abnormal.

pytorch vits
infer time : 10.691850900650024
RTF = 0.349893

onnx vits 
infer time : 4.495715618133545
RTF = 0.146124

onnx quantize vits
infer time : 83.49901461601257
RTF = 2.672614

**Comment by Masao-Someki** [comment]
Thank you for reporting the issue.
I realized this, but I'm not sure why this happens.
So as a workaround, if you don't have to use the quantization version, please use the un-quantized onnx model.

**Comment by Masao-Someki** [comment]
I found that converting the Conv module causes this problem.
I fixed this issue by limiting the nodes to quantize. Currently, only 'attention' and 'matmul' nodes will be quantized.
As a result, I got the following performance improvement.

- onnx vit (without quantize): 0.16759 sec
- onnx vit (quantized) : 0.12681 sec
