### ISSUE TITLE
why we need text_length in fastspeech2

### ISSUE THREAD

**Issue by Jackiexiao** [Masao-Someki/espnet_onnx#30]
Hi, thx for developing this repo

I am confused about `text_length` in the code below, why we need `text_length` in fastspeech2? Isn't text tensor enough?

https://github.com/Masao-Someki/espnet_onnx/blob/8bb9d7798b3b52b3b04c966a978d35c036c70ed7/espnet_onnx/export/tts/models/tts_models/fastspeech2.py#L136-L144

https://github.com/Masao-Someki/espnet_onnx/blob/8bb9d7798b3b52b3b04c966a978d35c036c70ed7/espnet_onnx/tts/tts_model.py#L48-L55

**Comment by Masao-Someki** [comment]
Hi, thank you for reporting the issue!
I didn't realize this... You are right, we don't need `text_length`.
I will fix this in the next tts PR!
