### ISSUE TITLE
Conformer-RNN Transducer model export onnx error

### ISSUE THREAD

**Issue by pengaoao** [Masao-Someki/espnet_onnx#41]
when i use https://github.com/espnet/espnet/tree/v.202205/egs2/librispeech/asr1 
the Conformer-RNN Transducer model
date: Fri Mar 25 04:35:42 EDT 2022
python version: 3.9.5 (default, Jun 4 2021, 12:28:51) [GCC 7.5.0]
espnet version: espnet 0.10.7a1
pytorch version: pytorch 1.8.1+cu111
Git hash: 21d19be00089678ca27f7fce474ef8d787689512
Commit date: Wed Mar 16 08:06:52 2022 -0400
ASR config: [conf/train_rnnt_conformer.yaml](https://github.com/espnet/espnet/blob/v.202205/egs2/librispeech/asr1/conf/train_rnnt_conformer.yaml)
Pretrained model: https://huggingface.co/espnet/chai_librispeech_asr_train_rnnt_conformer_raw_en_bpe5000_sp

to export onnx, i met the following error:
Traceback (most recent call last):
  File "export.py", line 30, in <module>
    m.export(speech2text, 'onnx_export', quantize=False)
  File "/home/p00510131/espnet_onnx/espnet_onnx/export/asr/export_asr.py", line 110, in export
    ctc_model = CTC(model.asr_model.ctc.ctc_lo)
AttributeError: 'NoneType' object has no attribute 'ctc_lo'

the export script is :
from espnet2.bin.asr_inference import Speech2Text
import os
import yaml
from espnet_onnx.export import ASRModelExport

m = ASRModelExport()
transducer_conf = yaml.safe_load(Path('espnet/egs2/librispeech/asr1/conf/decode_rnnt_conformer.yaml').read_text())
speech2text = Speech2Text(asr_train_config="exp/asr_train_rnnt_conformer_ngpu4_raw_en_bpe5000_sp/config.yaml",
                          asr_model_file="exp/asr_train_rnnt_conformer_ngpu4_raw_en_bpe5000_sp/valid.loss.ave_10best.pth",
                          transducer_conf=transducer_conf["transducer_conf"],
                          lm_weight=0.0
                          )

m.export(speech2text, 'onnx_export', quantize=False)

**Comment by Masao-Someki** [comment]
Hi @pengaoao, thank you for the issue.
I realize that we need to add an `if` sentence in the line to avoid the `ctc=None` case.
I'm planning to release a new version this weekend, so I will fix and include this in the release!
